paths:
  roms: roms
  models: working/models

training:
  game: Example-Nes-v0
  savestate: Level1
  render_mode: rgb_array
  fingerprint: replace-me
  runner_id: replace-me
  runner_name: replace-me

upload:
  url: https://speedlab.datenwissenschaften.com/api
  api_key: replace-me

log_level: INFO
